### ISSUE TITLE
Multiple RequestedPackages

### ISSUE THREAD

**Issue by ttcoelhoo** [dreipunktnull/dhl-express#5]
Thanks for sharing this good piece of work.
I was wondering how can you request multiple packages when requesting a shipment? Every time I try like this 
`new PackagesType([new RequestedPackagesType($weight, $dimensions, $customerReferences, $number), new RequestedPackagesType($weight, $dimensions, $customerReferences, $number)])` 

SOAP returns the error:

**SOAP-ERROR: Encoding: object has no 'Weight' property** 

If I print the ProcessShipmentRequestType Object the 'Packages' properties as an example would be something like:

```
[Packages:protected] => DHL\Express\Webservice\docTypeRef_PackagesType Object
                (
                    [RequestedPackages:protected] => Array
                        (
                            [0] => DHL\Express\Webservice\docTypeRef_RequestedPackagesType Object
                                (
                                    [InsuredValue:protected] => 
                                    [Weight:protected] => 2.0000
                                    [Dimensions:protected] => DHL\Express\Webservice\docTypeRef_DimensionsType Object
                                        (
                                            [Length:protected] => 37.5
                                            [Width:protected] => 21.5
                                            [Height:protected] => 13.2
                                        )

                                    [CustomerReferences:protected] => 41938
                                    [number:protected] => 4
                                    [PackageContentDescription:protected] => 
                                )

                            [1] => DHL\Express\Webservice\docTypeRef_RequestedPackagesType Object
                                (
                                    [InsuredValue:protected] => 
                                    [Weight:protected] => 2.0000
                                    [Dimensions:protected] => DHL\Express\Webservice\docTypeRef_DimensionsType Object
                                        (
                                            [Length:protected] => 37.5
                                            [Width:protected] => 21.5
                                            [Height:protected] => 13.2
                                        )

                                    [CustomerReferences:protected] => 41938
                                    [number:protected] => 4
                                    [PackageContentDescription:protected] => 
                                )

                        )

                )
```

I'm using PHP 7.0.17-2+deb.sury.org~trusty+1

**Comment by cedricziel** [comment]
TBH I never touched requesting multiple packages - it might be necessary on a current project so we might be able to solve this.

One thing we found during development, is,that the API is surprisingly unstable. - The SOAP endpoint itself that is - and we can never make be sure where a failure is really coming from.

I see your code and it makes sense to me, but I think I'll need to get back to you lateron, after we tackled this problem.

**Comment by ttcoelhoo** [comment]
Thanks @cedricziel,

I tested requesting with raw XML and it works.

eg.
`                <Packages>
                    <RequestedPackages number="2">
                        <Weight>2.0000</Weight>
                        <Dimensions>
                            <Length>10</Length>
                            <Width>20</Width>
                            <Height>30</Height>
                        </Dimensions>
                        <CustomerReferences>XXXX1</CustomerReferences>
                    </RequestedPackages>
                    <RequestedPackages number="3">
                        <Weight>4.0000</Weight>
                        <Dimensions>
                            <Length>40</Length>
                            <Width>50</Width>
                            <Height>60</Height>
                        </Dimensions>
                        <CustomerReferences>XXXX2</CustomerReferences>
                    </RequestedPackages>
                </Packages>`

But through the SoapClient it does not. and your SOAP API client classes also don't seem to be the problem.
I even considered if this couldn't be a PHP SoapClient class bug.

I also tried to convert the parameters object to XML string (like soap __getLastRequest method does) before the request so i could compare with the raw XML example above  but it looks like is not an easy thing to do.

**Comment by vicmar** [comment]
I'm having exactly the same problem. Did you find any solutions @ttcoelhoo @cedricziel ?
Thanks!

**Comment by thomasphansen** [comment]
JIC someone wants to resurrect this discussion: I spent (a lot of) time over the DHL Express (now MyDHL) WSDL definition - and I also maintain my own fork of wsdl2phpgenerator (whose original version was used to create the base code for this project). DHL makes a very aggressive usage of what is possible to do with the WSDL definition - IMO, dealing with it involves three big issues:

1 - DHL WSDL file relays severely on object inheritance (which means, one definition of an object relies partially on another object's definition). This is partially supported by wsdl2phpgenerator: it will work in some cases, but in others it will create useless classes for the descendants.

2 - There is a number of ways of describing a collection of objects inside a WSDL file. Wsdl2phpgenerator is able to handle some of them only - and the way the DHL file was build is unfortunately the most supported one. It works fine when you need to send a single element, but when you need to send multiple, the built structure will not fully match what the server is waiting, resulting in parsing errors on their side.

3 - the DHL WSDL file uses tons of "simpleType" definitions, mainly to add constrains to fields. While this is an OK practice, wsdl2generator knows NOTHING about how to handle it, and will simply create invalid type declarations all around for these guys. This is a pain in the neck for those using PhpStorm, which will see more than a thousand of errors in the generated library. And since our fork for wsdl2phpgenerator is php7-aware (using types all around), this becomes an even bigger issue...

Due to this, I am now working on a new approach for this library, based on the new MyDHL documentation, and relying on REST and guzzle. The new library is being built with [openapi-generator](https://github.com/OpenAPITools/openapi-generator), based on a swagger 2.0 file. So far, so good... When the library is ready for our needs, we will make it public at github.

**Comment by timrbetts** [comment]
I'm also running into this issue and was wondering if there was any workaround in constructing the RequestedPackages or Packages array in PHP for the __soapCall(). Is there some subtle way of introducing a 2nd RequestedPackages? The code I'm using works just fine for UPS Freight, Old Dominion, but DHL parsing always comes back with Weight not recognised whenever I tried to pass RequestedPackages as an array instead of just a single instance. I could construct the XML manually but I'm hoping I don't have to resort to that. Thanks for any advice.

**Comment by jmtalves** [comment]
hello, Has anyone found solution for this problem?
Thanks

**Comment by timrbetts** [comment]
I spoke with DHL integration support and they acknowledged the issue in the specification and were going to address it. In the meantime, this is what I did using XSD_ANYXML, essentially building the XML manually and building SoapVar's. 

```
$requestedPackages` = new ArrayObject();
for ($i = 0; $i < $num_items; $i++) {
  $xml  = '<RequestedPackages>';
  $xml .=   "<Weight><Value>" . $item_weight][$i] . "</Value></Weight>";
  $xml .=   "<Dimensions>";
  $xml .=     "<Length>" . $item_length[$i] . "</Length>";
  $xml .=     "<Width>" .  $item_width[$i] . "</Width>";
  $xml .=     "<Height>" . $item_height[$i] . "</Height>";
  $xml .=   "</Dimensions>";
  $xml .= "</RequestedPackages>";
  $requestedPackage = new SoapVar($xml, XSD_ANYXML);
  $requestedPackages->append($requestedPackage);
}
$packages = new SoapVar($requestedPackages, SOAP_ENC_OBJECT, null, null, "Packages");
$requestedShipment->Packages = $packages
```

Go easy on me. I don't claim this to be the best solution or anything since I'm still somewhat of a Soap rookie, but perhaps it helps someone. All the best.

**Comment by sentiasa** [comment]
@timrbetts Thanks for sharing and saving me hours if not days! :)

**Comment by alex-monte** [comment]
@timrbetts Thank you very much for your contribution. It has solved my problem. I was desperate with this problem with DHL's "ShipmentRequest" SOAP service and they gave me no solution. In my case I have had to modify it slightly, I attach it in case it helps someone:

   
        $cont = 1;
        foreach ($qtyPackages as $qtyP) {
            $xml  = '<RequestedPackages number="'.$cont.'">';
            $xml .=   '<Weight>'.$qtyP->weight.'</Weight>';
            $xml .=   '<Dimensions>';
            $xml .=     '<Length>'.$qtyP->length.'</Length>';
            $xml .=     '<Width>'.$qtyP->width.'</Width>';
            $xml .=     '<Height>'.$qtyP->height.'</Height>';
            $xml .=   '</Dimensions>';
            $xml .=   '<CustomerReferences>'.str_pad($cont, 5, '0', STR_PAD_LEFT).'</CustomerReferences>';
            $xml .= '</RequestedPackages>';
            $requestedPackage = new SoapVar($xml, XSD_ANYXML);
            $requestedPackages[] = $requestedPackage;
            $cont++;
        }
        $packages = new SoapVar($requestedPackages, SOAP_ENC_OBJECT, null, null, "Packages");
